// Run with: node test/run.js
const { replaceHen } = require('../hen.js');

// [mode, input, expected, optional ctx]
const cases = [
  // --- subject ---
  ['han', 'Hen kom hjem sent.', 'Han kom hjem sent.'],
  ['han', 'Hen er hjemme.', 'Han er hjemme.'],
  ['han', 'Hen selv sa det.', 'Han selv sa det.'],
  ['han', 'Hen og hun gikk hjem.', 'Han og hun gikk hjem.'],
  ['han', 'HEN kom.', 'HAN kom.'],
  // --- inverted subject (V2) ---
  ['han', 'Så gikk hen hjem.', 'Så gikk han hjem.'],
  ['han', 'Så gikk hen til døren.', 'Så gikk han til døren.'],
  ['han', 'Hva sier hen til det?', 'Hva sier han til det?'],
  ['han', 'Der står hen og venter.', 'Der står han og venter.'],
  ['han', 'Er hen hjemme?', 'Er han hjemme?'],
  ['han', 'Hvorfor kom ikke hen?', 'Hvorfor kom ikke han?'],
  ['han', 'Så skrek hen.', 'Så skrek han.'],
  ['han', 'Hvem er hen egentlig?', 'Hvem er han egentlig?'],
  ['han', 'Det var hen.', 'Det var han.'],
  // --- subordinate clauses ---
  ['han', 'Når hen kommer, ringer jeg.', 'Når han kommer, ringer jeg.'],
  ['han', 'Jeg tror hen kommer.', 'Jeg tror han kommer.'],
  ['han', 'Jeg skjønte ikke hva hen mente.', 'Jeg skjønte ikke hva han mente.'],
  ['han', 'Per og hen gikk på kino.', 'Per og han gikk på kino.'],
  // --- object ---
  ['han', 'Jeg møtte hen i går.', 'Jeg møtte ham i går.'],
  ['han', 'Jeg lot hen gjøre det.', 'Jeg lot ham gjøre det.'],
  ['han', 'Hun la hen i sengen.', 'Hun la ham i sengen.'],
  ['han', 'Jeg ga hen en gave.', 'Jeg ga ham en gave.'],
  ['han', 'Jeg ser ikke hen.', 'Jeg ser ikke ham.'],
  ['han', 'Jeg skal hente hen.', 'Jeg skal hente ham.'],
  ['han', 'Hent hen fra skolen.', 'Hent ham fra skolen.'],
  ['han', 'Jeg møtte Per og hen.', 'Jeg møtte Per og ham.'],
  ['han', 'Jeg snakket med hen om det.', 'Jeg snakket med ham om det.'],
  ['han', 'Gi det til hen.', 'Gi det til ham.'],
  ['han', 'Han ble sint på hen.', 'Han ble sint på ham.'],
  ['han', 'Møtte jeg hen i går?', 'Møtte jeg ham i går?'],
  ['hun', 'Jeg møtte hen i går.', 'Jeg møtte henne i går.'],
  // --- possessive ---
  ['han', 'Det er hens bok.', 'Det er hans bok.'],
  ['hun', 'Det er hens bok.', 'Det er hennes bok.'],
  ['slash', 'Hens bok ligger der.', 'Hans/hennes bok ligger der.'],
  // --- slash mode ---
  ['slash', 'Hen kom.', 'Han/hun kom.'],
  ['slash', 'Jeg møtte hen.', 'Jeg møtte ham/henne.'],
  ['slash', 'HEN kom.', 'HAN/HUN kom.'],
  // --- multiple sentences ---
  ['han', 'Jeg møtte hen. Hen smilte.', 'Jeg møtte ham. Han smilte.'],
  // --- must stay unchanged: adverb idioms ---
  ['han', 'Han gikk hen til døren.', 'Han gikk hen til døren.'],
  ['han', 'Han gikk hen og sa det.', 'Han gikk hen og sa det.'],
  ['han', 'La det stå hen.', 'La det stå hen.'],
  ['han', 'Han falt hen i søvn.', 'Han falt hen i søvn.'],
  ['han', 'Det ble sendt hen i det uvisse.', 'Det ble sendt hen i det uvisse.'],
  // --- must stay unchanged: look-alikes ---
  ['han', 'Han henvendte seg til henne.', 'Han henvendte seg til henne.'],
  ['han', 'Han hentet henne og hengte opp jakken.', 'Han hentet henne og hengte opp jakken.'],
  ['han', 'Ordet hen-pronomen er nytt.', 'Ordet hen-pronomen er nytt.'],
  // --- context across text-node boundaries (e.g. <b>hen</b>) ---
  ['han', 'hen', 'ham', { before: 'Jeg møtte ', after: '.' }],
  ['han', 'Hen', 'Han', { before: '', after: ' kom.' }],
  ['han', 'hen', 'han', { before: 'Så gikk ', after: ' hjem.' }],
  // --- interrogative adverb "hvor ... hen" must stay unchanged ---
  ['han', 'Hvor skal du hen?', 'Hvor skal du hen?'],
  ['han', 'Jeg vet ikke hvor du skal hen.', 'Jeg vet ikke hvor du skal hen.'],
  ['han', 'Hvor bor du hen?', 'Hvor bor du hen?'],
  ['han', 'Hvor har du bodd hen?', 'Hvor har du bodd hen?'],
  ['han', 'Hvor skal du egentlig hen?', 'Hvor skal du egentlig hen?'],
  ['han', 'Hvor kan jeg dra hen?', 'Hvor kan jeg dra hen?'],
  ['han', 'Hvor flyttet de hen i fjor?', 'Hvor flyttet de hen i fjor?'],
  ['han', 'Kvar skal du hen?', 'Kvar skal du hen?'],
  ['han', 'Det er adverbet hen.', 'Det er adverbet hen.'],
  // --- "hvor" with the pronoun must still be rewritten ---
  ['han', 'Hvor bodde hen?', 'Hvor bodde han?'],
  ['han', 'Hvor tror du hen bor?', 'Hvor tror du han bor?'],
  ['han', 'Hvor ofte ser du hen?', 'Hvor ofte ser du ham?'],
  ['han', 'Hvor kjenner du hen fra?', 'Hvor kjenner du ham fra?'],
  ['han', 'Hvor reiste du med hen?', 'Hvor reiste du med ham?'],
  ['han', 'Hvor skal du møte hen?', 'Hvor skal du møte ham?'],
  ['han', 'Hvor gammel er hen?', 'Hvor gammel er han?'],
  ['hun', 'Hvor har du sett hen?', 'Hvor har du sett henne?'],
  // --- Nynorsk (ctx.lang = 'nn'): ho / han (object) / hennar ---
  ['hun', 'Hen er fødd i 1991.', 'Ho er fødd i 1991.', { lang: 'nn' }],
  ['hun', 'Eg har ikkje sett hen her på lenge.', 'Eg har ikkje sett henne her på lenge.', { lang: 'nn' }],
  ['han', 'Eg har ikkje sett hen her på lenge.', 'Eg har ikkje sett han her på lenge.', { lang: 'nn' }],
  ['slash', 'Hen var her i går.', 'Han/ho var her i går.', { lang: 'nn' }],
  ['slash', 'Eg møtte hen i går.', 'Eg møtte han/henne i går.', { lang: 'nn' }],
  ['slash', 'Eg har gløymt namnet hens.', 'Eg har gløymt namnet hans/hennar.', { lang: 'nn' }],
  ['hun', 'Det er hens bok.', 'Det er hennar bok.', { lang: 'nn' }],
  ['hun', 'Eg trur hen kjem.', 'Eg trur ho kjem.', { lang: 'nn' }],
  ['hun', 'Kva seier hen?', 'Kva seier ho?', { lang: 'nn' }],
  ['hun', 'Korleis ser objektsforma av hen ut?', 'Korleis ser objektsforma av henne ut?', { lang: 'nn' }],
  ['hun', 'Blir studenten teken i fusk, kan hen bli utestengd.', 'Blir studenten teken i fusk, kan ho bli utestengd.', { lang: 'nn' }],
  ['hun', 'Eg gav hen ei gåve frå dei.', 'Eg gav henne ei gåve frå dei.', { lang: 'nn' }],
  ['hun', 'Eg snakka med hen.', 'Eg snakka med henne.', { lang: 'nn' }],
  ['hun', 'Hen gjekk heim.', 'Ho gjekk heim.', { lang: 'nn' }],
  ['hun', 'Han gjekk hen til døra.', 'Han gjekk hen til døra.', { lang: 'nn' }],
  ['hun', 'Kvar skal du hen?', 'Kvar skal du hen?', { lang: 'nn' }],
  ['hun', 'Kvar budde hen?', 'Kvar budde ho?', { lang: 'nn' }],
  ['hun', 'Eg veit ikkje kvar du bur hen.', 'Eg veit ikkje kvar du bur hen.', { lang: 'nn' }],
  // Bokmål is unaffected by an explicit lang = 'nb'
  ['hun', 'Jeg møtte hen i går.', 'Jeg møtte henne i går.', { lang: 'nb' }],
  ['hun', 'Hen er hjemme.', 'Hun er hjemme.', { lang: 'nb' }],
  // --- V2 inversion after a fronted adverbial / PP ---
  ['hun', 'I dag kom hen sent hjem.', 'I dag kom hun sent hjem.'],
  ['hun', 'I går møtte hen Per på kafé.', 'I går møtte hun Per på kafé.'],
  ['hun', 'Etter skolen gikk hen rett hjem.', 'Etter skolen gikk hun rett hjem.'],
  ['hun', 'Samme kveld ringte hen til meg.', 'Samme kveld ringte hun til meg.'],
  ['hun', 'Neste dag reiste hen.', 'Neste dag reiste hun.'],
  ['hun', 'Til slutt tok hen med seg jakken.', 'Til slutt tok hun med seg jakken.'],
  ['hun', 'På kontoret jobber hen med regnskap.', 'På kontoret jobber hun med regnskap.'],
  ['hun', 'Og i dag kom hen.', 'Og i dag kom hun.'],
  ['hun', 'Hvor mye tjener hen?', 'Hvor mye tjener hun?'],
  ['hun', 'Hva planlegger hen å gjøre?', 'Hva planlegger hun å gjøre?'],
  ['hun', '«Jeg kommer snart», hvisket hen.', '«Jeg kommer snart», hvisket hun.'],
  ['hun', '«Hei» utbrøt hen.', '«Hei» utbrøt hun.'],
  ['hun', '"Hei", utbrøt hen.', '"Hei", utbrøt hun.'],
  ['hun', '– Hei, sa hen.', '– Hei, sa hun.'],
  ['hun', 'Når det var over, møtte hen Per.', 'Når det var over, møtte hun Per.'],
  // ... but a noun subject before the verb keeps hen an object
  ['hun', 'Men Per møtte hen.', 'Men Per møtte henne.'],
  ['hun', 'Og Per møtte hen.', 'Og Per møtte henne.'],
  ['hun', 'Da Per møtte hen, ble han glad.', 'Da Per møtte henne, ble han glad.'],
  ['hun', 'Jeg vet at Per møtte hen.', 'Jeg vet at Per møtte henne.'],
  ['hun', 'Hun hilste på dem som møtte hen.', 'Hun hilste på dem som møtte henne.'],
  ['hun', 'Etter at Per kom, ringte vi hen.', 'Etter at Per kom, ringte vi henne.'],
  // --- imperatives vs. questions ---
  ['hun', 'La hen gjøre det selv.', 'La henne gjøre det selv.'],
  ['hun', 'Spør hen om hjelp.', 'Spør henne om hjelp.'],
  ['hun', 'Gjør hen glad.', 'Gjør henne glad.'],
  ['hun', 'Ikke spør hen om det.', 'Ikke spør henne om det.'],
  ['hun', 'Ikke la hen gå alene.', 'Ikke la henne gå alene.'],
  ['hun', 'Ring hen i morgen.', 'Ring henne i morgen.'],
  ['hun', 'Finn hen i mengden.', 'Finn henne i mengden.'],
  ['hun', 'Skriv hen en melding.', 'Skriv henne en melding.'],
  ['hun', 'Hei! Spør hen om hjelp.', 'Hei! Spør henne om hjelp.'],
  ['hun', '"Spør hen", sa han.', '"Spør henne", sa han.'],
  ['hun', 'Spør hen deg om noe?', 'Spør hun deg om noe?'],
  ['hun', 'Kommer hen i dag?', 'Kommer hun i dag?'],
  ['hun', 'Gikk hen til døren?', 'Gikk hun til døren?'],
  // --- coordinated pronouns copy each other's case ---
  ['hun', 'Han, hun eller hen kan søke.', 'Han, hun eller hun kan søke.'],
  ['hun', 'Enten han, hun eller hen er først.', 'Enten han, hun eller hun er først.'],
  ['hun', 'Han/hun/hen er velkommen.', 'Han/hun/hun er velkommen.'],
  ['hun', 'Han eller hen.', 'Han eller hun.'],
  ['hun', 'Jeg møtte ham, henne og hen.', 'Jeg møtte ham, henne og henne.'],
  ['hun', 'Jeg ga det til meg og hen.', 'Jeg ga det til meg og henne.'],
  ['hun', 'Jeg møtte ham, hen kom senere.', 'Jeg møtte ham, hun kom senere.'],
  // --- adverbs between hen and the verb ---
  ['hun', 'Jeg tror hen ikke kommer.', 'Jeg tror hun ikke kommer.'],
  ['hun', 'Om hen ikke kommer, ringer jeg.', 'Om hun ikke kommer, ringer jeg.'],
  ['hun', 'Siden hen også er syk, blir vi hjemme.', 'Siden hun også er syk, blir vi hjemme.'],
  ['hun', 'Jeg tror hen bare er sliten.', 'Jeg tror hun bare er sliten.'],
  ['hun', 'Jeg møtte hen ikke i går.', 'Jeg møtte henne ikke i går.'],
  ['hun', 'Jeg ser hen aldri.', 'Jeg ser henne aldri.'],
  // --- verbs that take a clause: hen is the subject even before an unlisted verb ---
  ['hun', 'Jeg tror hen planlegger en tur.', 'Jeg tror hun planlegger en tur.'],
  ['hun', 'Jeg mener hen fortjener bedre.', 'Jeg mener hun fortjener bedre.'],
  ['hun', 'Jeg ga hen bøker til jul.', 'Jeg ga henne bøker til jul.'],
  ['hun', 'Jeg forstår hen godt.', 'Jeg forstår henne godt.'],
  ['hun', 'Eg trur hen planlegg ein tur.', 'Eg trur ho planlegg ein tur.', { lang: 'nn' }],
  // --- more adverb idioms ---
  ['hun', 'Det varte langt hen på natta.', 'Det varte langt hen på natta.'],
  ['hun', 'Han kom hen til meg.', 'Han kom hen til meg.'],
  ['hun', 'Hun løp hen til døren.', 'Hun løp hen til døren.'],
  ['hun', 'Vi skal dra hen til dem.', 'Vi skal dra hen til dem.'],
  ['hun', 'Gå hen til døren.', 'Gå hen til døren.'],
  ['hun', 'Hvor går du hen?', 'Hvor går du hen?'],
  ['hun', 'I går kom hen til meg.', 'I går kom hun til meg.'],
  ['hun', 'Så kom hen til meg.', 'Så kom hun til meg.'],
  // --- tokens that merely contain "hen" ---
  ['hun', 'Besøk www.hen.no for mer.', 'Besøk www.hen.no for mer.'],
  ['hun', 'Følg #hen på Instagram.', 'Følg #hen på Instagram.'],
  ['hun', 'Skriv til @hen.', 'Skriv til @hen.'],
  ['hun', 'Send e-post til hen@eksempel.no.', 'Send e-post til hen@eksempel.no.'],
  ['hun', 'Kontakt kari.hen@firma.no.', 'Kontakt kari.hen@firma.no.'],
  ['hun', 'Åpne filen hen.txt.', 'Åpne filen hen.txt.'],
  ['hun', 'Jeg møtte hen. Hen smilte.', 'Jeg møtte henne. Hun smilte.'],
  ['hun', 'og så...hen kom', 'og så...hun kom'],
  // --- misc ---
  ['hun', 'HENS BOK', 'HENNES BOK'],
  ['hun', 'Hen sa: «Jeg kommer.»', 'Hun sa: «Jeg kommer.»'],
  ['hun', 'Per, som hen kjenner godt, kommer.', 'Per, som hun kjenner godt, kommer.'],
  ['hun', 'Det er hen som bestemmer.', 'Det er hun som bestemmer.'],
  ['hun', 'Hen, som er lærer, kom.', 'Hun, som er lærer, kom.'],
  ['hun', 'Alle likte hen.', 'Alle likte henne.'],
  ['hun', 'Hva ga du hen?', 'Hva ga du henne?'],
  ['hun', 'Hvem sendte brevet til hen?', 'Hvem sendte brevet til henne?'],
  ['hun', 'hen', 'hun'],
  ['hun', 'Hen!', 'Hun!'],
  // --- regressions found in running text ---
  ['hun', 'For hen er det viktig å bli sett.', 'For henne er det viktig å bli sett.'],
  ['hun', 'For hen betyr det mye.', 'For henne betyr det mye.'],
  ['hun', 'Jeg ble hjemme, for hen var syk.', 'Jeg ble hjemme, for hun var syk.'],
  ['hun', 'Alle som kjenner hen vet at hen alltid kommer for sent.', 'Alle som kjenner henne vet at hun alltid kommer for sent.'],
  ['hun', 'De som møter hen blir glade.', 'De som møter henne blir glade.'],
  ['hun', 'Jeg vet hvem som sa hen kom.', 'Jeg vet hvem som sa hun kom.'],
  ['hun', 'Når kommer hen?', 'Når kommer hun?'],
  ['hun', 'Da kom hen.', 'Da kom hun.'],
  // --- Nynorsk V2 / relative / imperative / lists ---
  ['hun', 'Etter skulen gjekk hen rett heim.', 'Etter skulen gjekk ho rett heim.', { lang: 'nn' }],
  ['hun', 'I dag kom hen heim.', 'I dag kom ho heim.', { lang: 'nn' }],
  ['hun', 'Spør hen om hjelp.', 'Spør henne om hjelp.', { lang: 'nn' }],
  ['hun', 'Eg trur hen ikkje kjem.', 'Eg trur ho ikkje kjem.', { lang: 'nn' }],
  ['hun', 'Alle som kjenner hen veit det.', 'Alle som kjenner henne veit det.', { lang: 'nn' }],
  ['hun', 'Han, ho eller hen kan søkje.', 'Han, ho eller ho kan søkje.', { lang: 'nn' }],
  ['hun', '«Eg kjem snart», kviskra hen.', '«Eg kjem snart», kviskra ho.', { lang: 'nn' }],
  ['hun', 'For hen er det viktig.', 'For henne er det viktig.', { lang: 'nn' }],
  // --- "han eller hun": slash mode with "eller" ---
  ['eller', 'Hen kom.', 'Han eller hun kom.'],
  ['eller', 'Jeg møtte hen.', 'Jeg møtte ham eller henne.'],
  ['eller', 'Det er hens bok.', 'Det er hans eller hennes bok.'],
  ['eller', 'HEN kom.', 'HAN ELLER HUN kom.'],
  ['eller', 'HENS BOK', 'HANS ELLER HENNES BOK'],
  ['eller', 'Jeg møtte hen. Hen smilte.', 'Jeg møtte ham eller henne. Han eller hun smilte.'],
  ['eller', 'Han gikk hen til døren.', 'Han gikk hen til døren.'],
  ['eller', 'Hen var her i går.', 'Han eller ho var her i går.', { lang: 'nn' }],
  ['eller', 'Eg møtte hen i går.', 'Eg møtte han eller henne i går.', { lang: 'nn' }],
  ['eller', 'Eg har gløymt namnet hens.', 'Eg har gløymt namnet hans eller hennar.', { lang: 'nn' }],
  // --- vedkommende (vedkomande in Nynorsk): same form for subject and object ---
  ['vedkommende', 'Hen kom hjem sent.', 'Vedkommende kom hjem sent.'],
  ['vedkommende', 'Jeg møtte hen i går.', 'Jeg møtte vedkommende i går.'],
  ['vedkommende', 'Gi det til hen.', 'Gi det til vedkommende.'],
  ['vedkommende', 'Det er hens bok.', 'Det er vedkommendes bok.'],
  ['vedkommende', 'HEN kom.', 'VEDKOMMENDE kom.'],
  ['vedkommende', 'HENS BOK', 'VEDKOMMENDES BOK'],
  ['vedkommende', 'Jeg møtte hen. Hen smilte.', 'Jeg møtte vedkommende. Vedkommende smilte.'],
  ['vedkommende', 'hen', 'vedkommende', { before: 'Jeg møtte ', after: '.' }],
  ['vedkommende', 'Han gikk hen til døren.', 'Han gikk hen til døren.'],
  ['vedkommende', 'Hvor skal du hen?', 'Hvor skal du hen?'],
  ['vedkommende', 'Han henvendte seg til henne.', 'Han henvendte seg til henne.'],
  ['vedkommende', 'Hen kom heim.', 'Vedkomande kom heim.', { lang: 'nn' }],
  ['vedkommende', 'Eg møtte hen i går.', 'Eg møtte vedkomande i går.', { lang: 'nn' }],
  ['vedkommende', 'Det er hens bok.', 'Det er vedkomandes bok.', { lang: 'nn' }],
  ['vedkommende', 'HEN kom.', 'VEDKOMANDE kom.', { lang: 'nn' }],
  ['vedkommende', 'Han gjekk hen til døra.', 'Han gjekk hen til døra.', { lang: 'nn' }],
  ['vedkommende', 'Hen kom hjem sent.', 'Vedkommende kom hjem sent.', { lang: 'nb' }],
];

let failed = 0;
for (const [mode, input, expected, ctx] of cases) {
  const got = replaceHen(input, mode, ctx);
  if (got !== expected) {
    failed++;
    console.log(`FAIL [${mode}] ${input}\n  expected: ${expected}\n  got:      ${got}`);
  }
}
console.log(`${cases.length - failed}/${cases.length} passed`);
process.exit(failed ? 1 : 0);
